package defpackage;

import com.huawei.health.trusport_ee_jni.trusport_eeJNI;

/* loaded from: classes4.dex */
public final class gll {

    /* renamed from: a, reason: collision with root package name */
    public static final gll f12850a;
    public static final gll aa;
    public static final gll ab;
    public static final gll ac;
    public static final gll ad;
    public static final gll ae;
    public static final gll af;
    public static final gll ag;
    public static final gll ah;
    public static final gll ai;
    public static final gll aj;
    public static final gll ak;
    public static final gll al;
    public static final gll am;
    public static final gll an;
    public static final gll ao;
    public static final gll ap;
    public static final gll aq;
    public static final gll ar;
    public static final gll as;
    public static final gll at;
    public static final gll au;
    public static final gll av;
    public static final gll aw;
    public static final gll ax;
    public static final gll ay;
    public static final gll az;
    public static final gll b;
    public static final gll ba;
    public static final gll bb;
    public static final gll bc;
    public static final gll bd;
    public static final gll be;
    public static final gll bf;
    public static final gll bg;
    public static final gll bh;
    public static final gll bi;
    public static final gll bj;
    public static final gll bk;
    public static final gll bl;
    public static final gll bm;
    public static final gll bn;
    public static final gll bo;
    public static final gll bp;
    public static final gll bq;
    public static final gll br;
    public static final gll bs;
    public static final gll bt;
    public static final gll bu;
    public static final gll bv;
    public static final gll bw;
    public static final gll bx;
    public static final gll by;
    public static final gll bz;
    public static final gll c;
    public static final gll ca;
    public static final gll cb;
    public static final gll cc;
    public static final gll cd;
    public static final gll ce;
    public static final gll cf;
    public static final gll cg;
    public static final gll ch;
    public static final gll ci;
    public static final gll cj;
    public static final gll ck;
    public static final gll cl;
    public static final gll cm;
    public static final gll cn;
    public static final gll co;
    public static final gll cp;
    public static final gll cq;
    public static final gll cr;
    public static final gll cs;
    public static final gll ct;
    public static final gll cu;
    public static final gll cv;
    public static final gll cw;
    public static final gll cx;
    public static final gll cy;
    public static final gll cz;
    public static final gll d;
    public static final gll da;
    public static final gll db;
    public static final gll dc;
    public static final gll dd;
    public static final gll de;
    public static final gll df;
    private static int di;
    private static gll[] dj;
    public static final gll dk;
    public static final gll e;
    public static final gll f;
    public static final gll g;
    public static final gll h;
    public static final gll i;
    public static final gll j;
    public static final gll k;
    public static final gll l;
    public static final gll m;
    public static final gll n;
    public static final gll o;
    public static final gll p;
    public static final gll q;
    public static final gll r;
    public static final gll s;
    public static final gll t;
    public static final gll u;
    public static final gll v;
    public static final gll w;
    public static final gll x;
    public static final gll y;
    public static final gll z;
    private final String dg;
    private final int dh;

    static {
        gll gllVar = new gll("TS_ACTIVITY_OUTDOOR_RUN", trusport_eeJNI.TS_ACTIVITY_OUTDOOR_RUN_get());
        bq = gllVar;
        gll gllVar2 = new gll("TS_ACTIVITY_INDOOR_RUN");
        ay = gllVar2;
        gll gllVar3 = new gll("TS_ACTIVITY_OUTDOOR_WALK");
        br = gllVar3;
        gll gllVar4 = new gll("TS_ACTIVITY_INDOOR_WALK");
        ba = gllVar4;
        gll gllVar5 = new gll("TS_ACTIVITY_OUTDOOR_CYCLE");
        bo = gllVar5;
        gll gllVar6 = new gll("TS_ACTIVITY_INDOOR_CYCLE");
        au = gllVar6;
        gll gllVar7 = new gll("TS_ACTIVITY_ELLIPTICAL");
        ac = gllVar7;
        gll gllVar8 = new gll("TS_ACTIVITY_ROWER");
        by = gllVar8;
        gll gllVar9 = new gll("TS_ACTIVITY_POOL_SWIM");
        bx = gllVar9;
        gll gllVar10 = new gll("TS_ACTIVITY_OPEN_WATER_SWIM");
        bk = gllVar10;
        gll gllVar11 = new gll("TS_ACTIVITY_MOUNTAIN_HIKE");
        bi = gllVar11;
        gll gllVar12 = new gll("TS_ACTIVITY_HIKE");
        aq = gllVar12;
        gll gllVar13 = new gll("TS_ACTIVITY_TRAIL_RUN");
        cy = gllVar13;
        gll gllVar14 = new gll("TS_ACTIVITY_TRIATHLON");
        df = gllVar14;
        gll gllVar15 = new gll("TS_ACTIVITY_OTHER");
        bl = gllVar15;
        gll gllVar16 = new gll("TS_ACTIVITY_SKIING");
        ck = gllVar16;
        gll gllVar17 = new gll("TS_ACTIVITY_SNOWBOARDING");
        ch = gllVar17;
        gll gllVar18 = new gll("TS_ACTIVITY_CROSS_COUNTRY_SKIING");
        y = gllVar18;
        gll gllVar19 = new gll("TS_ACTIVITY_DRIVING_RANGE");
        aa = gllVar19;
        gll gllVar20 = new gll("TS_ACTIVITY_GOLF_COURSE");
        aj = gllVar20;
        gll gllVar21 = new gll("TS_ACTIVITY_JUMP_ROPE");
        bc = gllVar21;
        gll gllVar22 = new gll("TS_ACTIVITY_FREEDIVING");
        af = gllVar22;
        gll gllVar23 = new gll("TS_ACTIVITY_BREATHHOLD");
        s = gllVar23;
        gll gllVar24 = new gll("TS_ACTIVITY_STRENGTH");
        cv = gllVar24;
        gll gllVar25 = new gll("TS_ACTIVITY_SPINNING");
        cn = gllVar25;
        gll gllVar26 = new gll("TS_ACTIVITY_STEPPER");
        cp = gllVar26;
        gll gllVar27 = new gll("TS_ACTIVITY_AIR_WALKER");
        c = gllVar27;
        gll gllVar28 = new gll("TS_ACTIVITY_HIIT");
        as = gllVar28;
        gll gllVar29 = new gll("TS_ACTIVITY_AEROBICS");
        e = gllVar29;
        gll gllVar30 = new gll("TS_ACTIVITY_GROUP_TRAINING");
        an = gllVar30;
        gll gllVar31 = new gll("TS_ACTIVITY_YOGA");
        dk = gllVar31;
        gll gllVar32 = new gll("TS_ACTIVITY_PILATES");
        bw = gllVar32;
        gll gllVar33 = new gll("TS_ACTIVITY_CROSS_FIT");
        w = gllVar33;
        gll gllVar34 = new gll("TS_ACTIVITY_FUNCTIONAL_TRAINING");
        am = gllVar34;
        gll gllVar35 = new gll("TS_ACTIVITY_PHYSICAL_TRAINING");
        bv = gllVar35;
        gll gllVar36 = new gll("TS_ACTIVITY_TAEKWONDO");
        cx = gllVar36;
        gll gllVar37 = new gll("TS_ACTIVITY_BOXING");
        r = gllVar37;
        gll gllVar38 = new gll("TS_ACTIVITY_FREE_SPARRING");
        ai = gllVar38;
        gll gllVar39 = new gll("TS_ACTIVITY_KARATE");
        az = gllVar39;
        gll gllVar40 = new gll("TS_ACTIVITY_FENCING");
        ae = gllVar40;
        gll gllVar41 = new gll("TS_ACTIVITY_CORE_TRAINING");
        p = gllVar41;
        gll gllVar42 = new gll("TS_ACTIVITY_BODY_COMBAT");
        n = gllVar42;
        gll gllVar43 = new gll("TS_ACTIVITY_KENDO");
        bf = gllVar43;
        gll gllVar44 = new gll("TS_ACTIVITY_SINGLE_BAR");
        cc = gllVar44;
        gll gllVar45 = new gll("TS_ACTIVITY_PARALLEL_BARS");
        bp = gllVar45;
        gll gllVar46 = new gll("TS_ACTIVITY_BELLY_DANCE");
        g = gllVar46;
        gll gllVar47 = new gll("TS_ACTIVITY_JAZZ_DANCE");
        bb = gllVar47;
        gll gllVar48 = new gll("TS_ACTIVITY_LATIN_DANCE");
        bg = gllVar48;
        gll gllVar49 = new gll("TS_ACTIVITY_BALLET");
        h = gllVar49;
        gll gllVar50 = new gll("TS_ACTIVITY_STREET_DANCE");
        co = gllVar50;
        gll gllVar51 = new gll("TS_ACTIVITY_PLAZA_DANCING");
        bu = gllVar51;
        gll gllVar52 = new gll("TS_ACTIVITY_DANCE");
        x = gllVar52;
        gll gllVar53 = new gll("TS_ACTIVITY_ROLLER_SKATING");
        cb = gllVar53;
        gll gllVar54 = new gll("TS_ACTIVITY_MARTIAL_ARTS");
        bd = gllVar54;
        gll gllVar55 = new gll("TS_ACTIVITY_TAI_CHI");
        cz = gllVar55;
        gll gllVar56 = new gll("TS_ACTIVITY_HULA_HOOP");
        aw = gllVar56;
        gll gllVar57 = new gll("TS_ACTIVITY_FRISBEE");
        ak = gllVar57;
        gll gllVar58 = new gll("TS_ACTIVITY_DARTS");
        ad = gllVar58;
        gll gllVar59 = new gll("TS_ACTIVITY_ARCHERY");
        b = gllVar59;
        gll gllVar60 = new gll("TS_ACTIVITY_HORSE_RIDING");
        ar = gllVar60;
        gll gllVar61 = new gll("TS_ACTIVITY_LASER_TAG");
        be = gllVar61;
        gll gllVar62 = new gll("TS_ACTIVITY_KITE_FLYING");
        bh = gllVar62;
        gll gllVar63 = new gll("TS_ACTIVITY_TUG_OF_WAR");
        dc = gllVar63;
        gll gllVar64 = new gll("TS_ACTIVITY_SWINGING");
        cs = gllVar64;
        gll gllVar65 = new gll("TS_ACTIVITY_STAIR_CLIMBING");
        cm = gllVar65;
        gll gllVar66 = new gll("TS_ACTIVITY_OBSTACLE_RACE");
        bm = gllVar66;
        gll gllVar67 = new gll("TS_ACTIVITY_FISHING");
        ah = gllVar67;
        gll gllVar68 = new gll("TS_ACTIVITY_BADMINTON");
        d = gllVar68;
        gll gllVar69 = new gll("TS_ACTIVITY_TABLE_TENNIS");
        cw = gllVar69;
        gll gllVar70 = new gll("TS_ACTIVITY_TENNIS");
        da = gllVar70;
        gll gllVar71 = new gll("TS_ACTIVITY_POOL");
        bt = gllVar71;
        gll gllVar72 = new gll("TS_ACTIVITY_BOWLING");
        k = gllVar72;
        gll gllVar73 = new gll("TS_ACTIVITY_VOLLEYBALL");
        de = gllVar73;
        gll gllVar74 = new gll("TS_ACTIVITY_SHUTTLECOCK");
        cg = gllVar74;
        gll gllVar75 = new gll("TS_ACTIVITY_HANDBALL");
        ap = gllVar75;
        gll gllVar76 = new gll("TS_ACTIVITY_BASEBALL");
        i = gllVar76;
        gll gllVar77 = new gll("TS_ACTIVITY_SOFTBALL");
        ci = gllVar77;
        gll gllVar78 = new gll("TS_ACTIVITY_CRICKET");
        u = gllVar78;
        gll gllVar79 = new gll("TS_ACTIVITY_FOOTBALL");
        ag = gllVar79;
        gll gllVar80 = new gll("TS_ACTIVITY_BEACH_SOCCER");
        f = gllVar80;
        gll gllVar81 = new gll("TS_ACTIVITY_BEACH_VOLLEYBALL");
        j = gllVar81;
        gll gllVar82 = new gll("TS_ACTIVITY_GATEBALL");
        al = gllVar82;
        gll gllVar83 = new gll("TS_ACTIVITY_HOCKEY");
        ao = gllVar83;
        gll gllVar84 = new gll("TS_ACTIVITY_SQUASH");
        cq = gllVar84;
        gll gllVar85 = new gll("TS_ACTIVITY_SEPAK_TAKRAW");
        cf = gllVar85;
        gll gllVar86 = new gll("TS_ACTIVITY_DODGEBALL");
        ab = gllVar86;
        gll gllVar87 = new gll("TS_ACTIVITY_SAILING");
        ce = gllVar87;
        gll gllVar88 = new gll("TS_ACTIVITY_SURFING");
        cr = gllVar88;
        gll gllVar89 = new gll("TS_ACTIVITY_RAFTING");
        bz = gllVar89;
        gll gllVar90 = new gll("TS_ACTIVITY_DRAGON_BOATING");
        z = gllVar90;
        gll gllVar91 = new gll("TS_ACTIVITY_CANOEING");
        q = gllVar91;
        gll gllVar92 = new gll("TS_ACTIVITY_ROWING");
        cd = gllVar92;
        gll gllVar93 = new gll("TS_ACTIVITY_WATER_SCOOTER");
        db = gllVar93;
        gll gllVar94 = new gll("TS_ACTIVITY_SUP");
        ct = gllVar94;
        gll gllVar95 = new gll("TS_ACTIVITY_ICE_SKATING");
        at = gllVar95;
        gll gllVar96 = new gll("TS_ACTIVITY_ICE_HOCKEY");
        ax = gllVar96;
        gll gllVar97 = new gll("TS_ACTIVITY_CURLING");
        v = gllVar97;
        gll gllVar98 = new gll("TS_ACTIVITY_BOBSLEIGH");
        l = gllVar98;
        gll gllVar99 = new gll("TS_ACTIVITY_SLEDDING");
        cj = gllVar99;
        gll gllVar100 = new gll("TS_ACTIVITY_BIATHLON");
        o = gllVar100;
        gll gllVar101 = new gll("TS_ACTIVITY_SKATEBOARDING");
        cl = gllVar101;
        gll gllVar102 = new gll("TS_ACTIVITY_ROCK_CLIMBING");
        ca = gllVar102;
        gll gllVar103 = new gll("TS_ACTIVITY_BUNGEE_JUMPING");
        t = gllVar103;
        gll gllVar104 = new gll("TS_ACTIVITY_PARKOUR");
        bs = gllVar104;
        gll gllVar105 = new gll("TS_ACTIVITY_BMX");
        m = gllVar105;
        gll gllVar106 = new gll("TS_ACTIVITY_ORIENTEERING");
        bj = gllVar106;
        gll gllVar107 = new gll("TS_ACTIVITY_PARACHUTING");
        bn = gllVar107;
        gll gllVar108 = new gll("TS_ACTIVITY_AUTO_RACING");
        f12850a = gllVar108;
        gll gllVar109 = new gll("TS_ACTIVITY_SWIMMING");
        cu = gllVar109;
        gll gllVar110 = new gll("TS_ACTIVITY_IDLE");
        av = gllVar110;
        gll gllVar111 = new gll("TS_ACTIVITY_UNKNOWN");
        dd = gllVar111;
        dj = new gll[]{gllVar, gllVar2, gllVar3, gllVar4, gllVar5, gllVar6, gllVar7, gllVar8, gllVar9, gllVar10, gllVar11, gllVar12, gllVar13, gllVar14, gllVar15, gllVar16, gllVar17, gllVar18, gllVar19, gllVar20, gllVar21, gllVar22, gllVar23, gllVar24, gllVar25, gllVar26, gllVar27, gllVar28, gllVar29, gllVar30, gllVar31, gllVar32, gllVar33, gllVar34, gllVar35, gllVar36, gllVar37, gllVar38, gllVar39, gllVar40, gllVar41, gllVar42, gllVar43, gllVar44, gllVar45, gllVar46, gllVar47, gllVar48, gllVar49, gllVar50, gllVar51, gllVar52, gllVar53, gllVar54, gllVar55, gllVar56, gllVar57, gllVar58, gllVar59, gllVar60, gllVar61, gllVar62, gllVar63, gllVar64, gllVar65, gllVar66, gllVar67, gllVar68, gllVar69, gllVar70, gllVar71, gllVar72, gllVar73, gllVar74, gllVar75, gllVar76, gllVar77, gllVar78, gllVar79, gllVar80, gllVar81, gllVar82, gllVar83, gllVar84, gllVar85, gllVar86, gllVar87, gllVar88, gllVar89, gllVar90, gllVar91, gllVar92, gllVar93, gllVar94, gllVar95, gllVar96, gllVar97, gllVar98, gllVar99, gllVar100, gllVar101, gllVar102, gllVar103, gllVar104, gllVar105, gllVar106, gllVar107, gllVar108, gllVar109, gllVar110, gllVar111};
        di = 0;
    }

    public final int e() {
        return this.dh;
    }

    public String toString() {
        return this.dg;
    }

    private gll(String str) {
        this.dg = str;
        int i2 = di;
        di = i2 + 1;
        this.dh = i2;
    }

    private gll(String str, int i2) {
        this.dg = str;
        this.dh = i2;
        di = i2 + 1;
    }
}
