package defpackage;

import com.huawei.health.ecologydevice.networkclient.HealthEngineRequestManager;
import java.util.HashMap;

/* loaded from: classes.dex */
public class jac {
    private static final HashMap<String, String> b;

    static {
        HashMap<String, String> hashMap = new HashMap<>();
        b = hashMap;
        hashMap.put("healthRecommendUrl", "healthcloud");
        hashMap.put("activityUrl", "healthcloud");
        hashMap.put("messageCenterUrl", "healthcloud");
        hashMap.put("sportSuggestUrl", "healthcloud");
        hashMap.put("achievementUrl", "healthcloud");
        hashMap.put("healthCloudUrl", "healthcloud");
        hashMap.put("socialCloudUrl", "healthcloud");
        hashMap.put("socialCloudProfileUrl", "healthcloud");
        hashMap.put("socialCloudRankUrl", "healthcloud");
        hashMap.put("healthDeviceUrl", "healthcloud");
        hashMap.put("healthAPPToDeviceUrl", "healthcloud");
        hashMap.put("hilinkDevicePrimaryCloudUrl", "healthcloud");
        hashMap.put("hilinkDeviceStandbyCloudUrl", "healthcloud");
        hashMap.put("tradeService", "healthcloud");
        hashMap.put("healthcare", "healthcloud");
        hashMap.put("healthOperationUrl", "healthcloud");
        hashMap.put("healthOperationUrlCn", "healthcloud");
        hashMap.put("knowledgeUrl", "com.huawei.health");
        hashMap.put("knowledgeContextUrl", "com.huawei.health");
        hashMap.put("materialUrl", "com.huawei.health");
        hashMap.put(HealthEngineRequestManager.GRS_KEY, "com.huawei.health");
        hashMap.put("agreementservice", "com.huawei.health");
        hashMap.put("biOperation", "com.huawei.health");
        hashMap.put("getLatestVersion", "com.huawei.health");
        hashMap.put("userInfoAgreement", "com.huawei.health");
        hashMap.put("newVersionUrl", "com.huawei.health");
        hashMap.put("getToken", "com.huawei.health");
        hashMap.put("getBatchPluginUrl", "com.huawei.health");
        hashMap.put("getAgnssPluginUrl", "com.huawei.health");
        hashMap.put("getNewBatchPluginUrl", "com.huawei.health");
        hashMap.put("watchFace", "com.huawei.health.watchface");
        hashMap.put("watchFaceH5", "com.huawei.health.watchface");
        hashMap.put("Music", "com.huawei.cloud.music");
        hashMap.put("domainResourcephsVmall", "com.huawei.health");
        hashMap.put("domainVenusVmall", "com.huawei.health");
        hashMap.put("domainContentcenterDbankcdn", "com.huawei.health");
        hashMap.put("domainContentcenterDbankcdnNew", "com.huawei.health");
        hashMap.put("domainPassWalletHicloud", "com.huawei.health");
        hashMap.put("domainNjtestlf2Hwcloudtest", "com.huawei.health");
        hashMap.put("domainVcardmgtWalletHicloud", "com.huawei.health");
        hashMap.put("domainNjtestlf2Hwcloudtest", "com.huawei.health");
        hashMap.put("domainTsmHicloud", "com.huawei.health");
        hashMap.put("domainLfpaytest01Hwcloudtest", "com.huawei.health");
        hashMap.put("domainHealthVmall", "com.huawei.health");
        hashMap.put("domainAVmall", "com.huawei.health");
        hashMap.put("domainHealthrecommendHicloud", "com.huawei.health");
        hashMap.put("domainUrlCloudHuawei", "com.huawei.health");
        hashMap.put("domainUrlDreCloudHuawei", "com.huawei.health");
        hashMap.put("domainApiVmall", "com.huawei.health");
        hashMap.put("domainHwidVmall", "com.huawei.health");
        hashMap.put("domainMVmall", "com.huawei.health");
        hashMap.put("domainSearchVmallDetail", "com.huawei.health");
        hashMap.put("domainSearchVmallImg", "com.huawei.health");
        hashMap.put("domainGlobalSearch", "com.huawei.health");
        hashMap.put("domainOpenapiVmall", "com.huawei.health");
        hashMap.put("domainOpenapiSitVmall", "com.huawei.health");
        hashMap.put("domainWwwHuawei", "com.huawei.health");
        hashMap.put("domainCcpceConsumerHuawei", "com.huawei.health");
        hashMap.put("domainSettingHicloud", "com.huawei.health");
        hashMap.put("domainTsmServiceHicloud", "com.huawei.health");
        hashMap.put("marketingUrl", "com.huawei.health");
        hashMap.put("marketingGateWayUrl", "com.huawei.health");
        hashMap.put("knitRequest", "com.huawei.health");
        hashMap.put("domainThemeCloud", "com.huawei.health");
        hashMap.put("hiCloudUrl", "com.huawei.health");
        hashMap.put("domainClubHuawei", "com.huawei.health");
        hashMap.put("domainCnClubVmall", "com.huawei.health");
        hashMap.put("domainMessagecenterHicloud", "com.huawei.health");
        hashMap.put("domainMessagecenterHicloudNew", "com.huawei.health");
        hashMap.put("domainAppgalleryCloudHuawei", "com.huawei.health");
        hashMap.put("domainWapHispaceHicloud", "com.huawei.health");
        hashMap.put("domainTipsResDbankcdn", "com.huawei.health");
        hashMap.put("domainSmarthomeHicloud", "com.huawei.health");
        hashMap.put("appMarketUrl", "com.huawei.health");
        hashMap.put("appMarketRequestUrl", "com.huawei.health");
        hashMap.put("appMarketH5Url", "com.huawei.health");
        hashMap.put("appMarketCloudUrl", "com.huawei.health");
        hashMap.put("domainLogserviceHicloud", "com.huawei.health");
        hashMap.put("domainLogtransformHicloud", "com.huawei.health");
        hashMap.put("domainCcpcConsumerHuawei", "com.huawei.health");
        hashMap.put("domainPasscommonDrcnWalletHicloud", "com.huawei.health");
        hashMap.put("domainConsumerHuawei", "com.huawei.health");
        hashMap.put("domainPrivacyConsumerHuawei", "com.huawei.health");
        hashMap.put("domainLegalCloudHuawei", "com.huawei.health");
        hashMap.put("domainTipsResDbankcdn", "com.huawei.health");
        hashMap.put("domainHealthcommonHicloud", "com.huawei.health");
        hashMap.put("domainSnsHicloud", "com.huawei.health");
        hashMap.put("domainImHicloud", "com.huawei.health");
        hashMap.put("domainCisHicloud", "com.huawei.health");
        hashMap.put("domainQueryHicloud", "com.huawei.health");
        hashMap.put("domainNfcwsHicloud", "com.huawei.health");
        hashMap.put("domainHagHicloud", "com.huawei.health");
        hashMap.put("domainScopeOauth", "com.huawei.health");
        hashMap.put("ROOT", "com.huawei.cloud.hota");
        hashMap.put("helpCustomerUrl", "com.huawei.health");
        hashMap.put("domainKlgMapDtlUrl", "com.huawei.health");
        hashMap.put("SITEID", "health.oversea.beta");
        hashMap.put("SITEID", "health.oversea");
        hashMap.put("domainHealthCloudCommon", "com.huawei.health");
        hashMap.put("enterpriseUrl", "com.huawei.health");
        hashMap.put("domainTipsResDbankcdnNew", "com.huawei.health");
        hashMap.put("domainSportrankingHicloud", "com.huawei.health");
        hashMap.put("domainAccessTokenUrl", "com.huawei.health");
        hashMap.put("domainOAuthLogin", "com.huawei.health");
        hashMap.put("domainComplaintCenterUrl", "com.huawei.health");
        hashMap.put("domainHealthdataHicloud", "com.huawei.health");
        hashMap.put("domainQrcodeMatchRules", "com.huawei.health");
        hashMap.put("domainHuafenUrl", "com.huawei.health");
        hashMap.put("domainbroadoldurl", "com.huawei.health");
        hashMap.put("domainbroadnewurl", "com.huawei.health");
        hashMap.put("userAgreementDomain", "com.huawei.health");
        hashMap.put("psiUploadUrl", "com.huawei.health");
        hashMap.put("domainMyHuawei", "com.huawei.health");
        hashMap.put("domainMyHuaweiUpLogin", "com.huawei.health");
        hashMap.put("domainMyHuaweiOauthLogin", "com.huawei.health");
        hashMap.put("recordNumberQueryUrl", "com.huawei.health");
        hashMap.put("domainSportsuggestHicloud", "com.huawei.health");
    }

    public static String d(String str) {
        return b.get(str);
    }
}
