package com.huawei.haf.router.routes;

import com.huawei.haf.router.facade.model.RouteMeta;
import com.huawei.haf.router.facade.model.RouteType;
import com.huawei.haf.router.facade.template.RouteGroup;
import com.huawei.ui.main.stories.fitness.activity.active.KnitActiveHoursActivity;
import com.huawei.ui.main.stories.fitness.activity.active.KnitActiveRecordActivity;
import com.huawei.ui.main.stories.fitness.activity.calorie.FitnessCalorieDetailActivity;
import com.huawei.ui.main.stories.fitness.activity.coresleep.KnitRelaxActivity;
import com.huawei.ui.main.stories.fitness.activity.coresleep.KnitSleepDetailActivity;
import com.huawei.ui.main.stories.fitness.activity.coresleep.KnitSleepTightActivity;
import com.huawei.ui.main.stories.fitness.activity.coresleep.SeriesCourseListActivity;
import com.huawei.ui.main.stories.fitness.activity.distance.FitnessDistanceDetailActivity;
import com.huawei.ui.main.stories.fitness.activity.pressure.activity.PressureMeasureActivity;
import com.huawei.ui.main.stories.fitness.activity.pressurecalibrate.activity.PressureCalibrateActivity;
import com.huawei.ui.main.stories.fitness.activity.pressurecalibrate.activity.WifiDevicePressureCalibrateGuideActivity;
import com.huawei.ui.main.stories.fitness.activity.sportintensity.FitnessSportIntensityDetailActivity;
import com.huawei.ui.main.stories.fitness.activity.step.FitnessStepDetailActivity;
import com.huawei.ui.main.stories.fitness.util.ThreeCirclePretreatment;
import com.huawei.ui.main.stories.health.activity.healthdata.AddOrEditWeightUserActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.BarCodeScanningActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.BaseHealthDataActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.BloodMeasureHintActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.ClaimMeasureDataActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.ClaimMeasureNoDataActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.HealthDataHistoryActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.HealthDatasActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.InputBloodPressureActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.InputWeightActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.InvoiceApplicationActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.KnitBloodPressureActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.KnitPressureActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.LightFastingStatusActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightAiBodyDataActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightBodyDataActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightDetailActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightEditShareActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightGoalActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightGoalPreviewActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightUnitSettingActivity;
import com.huawei.ui.main.stories.health.activity.healthdata.WeightUserManagerActivity;
import com.huawei.ui.main.stories.history.GradeEvaluationDescriptionActivity;
import com.huawei.ui.main.stories.history.SportHistoryActivity;
import com.huawei.ui.main.stories.me.activity.PrivacyCenterActivity;
import com.huawei.ui.main.stories.me.activity.PrivacyTrainingStatisticsActivity;
import com.huawei.ui.main.stories.me.activity.thirdparty.HealthKitThirdPartyAccountAuthActivity;
import com.huawei.ui.main.stories.me.activity.thirdparty.ThirdPartySyncActivity;
import com.huawei.ui.main.stories.nps.activity.QuestionMainActivity;
import com.huawei.ui.main.stories.privacy.template.view.showdata.PrivacyDataModelActivity;
import com.huawei.ui.main.stories.route.activity.MyRouteDetailActivity;
import com.huawei.ui.main.stories.service.SleepServiceImpl;
import com.huawei.ui.main.stories.template.health.module.HealthDataDetailActivity;
import java.util.Map;

/* loaded from: classes.dex */
public final class AppRouter$$Group$$Main implements RouteGroup {
    @Override // com.huawei.haf.router.facade.template.RouteGroup
    public void loadInto(Map<String, RouteMeta> map) {
        map.put("/Main/AddOrEditWeightUserActivity", RouteMeta.build(RouteType.ACTIVITY, AddOrEditWeightUserActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/BarCodeScanningActivity", RouteMeta.build(RouteType.ACTIVITY, BarCodeScanningActivity.class, -1, 16777216, null));
        map.put("/Main/BaseHealthDataActivity", RouteMeta.build(RouteType.ACTIVITY, BaseHealthDataActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/BloodMeasureHintActivity", RouteMeta.build(RouteType.ACTIVITY, BloodMeasureHintActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/ClaimMeasureDataActivity", RouteMeta.build(RouteType.ACTIVITY, ClaimMeasureDataActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/ClaimMeasureNoDataActivity", RouteMeta.build(RouteType.ACTIVITY, ClaimMeasureNoDataActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/FitnessCalorieDetailActivity", RouteMeta.build(RouteType.ACTIVITY, FitnessCalorieDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/FitnessDistanceDetailActivity", RouteMeta.build(RouteType.ACTIVITY, FitnessDistanceDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/FitnessSportIntensityDetailActivity", RouteMeta.build(RouteType.ACTIVITY, FitnessSportIntensityDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/FitnessStepDetailActivity", RouteMeta.build(RouteType.ACTIVITY, FitnessStepDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/GradeEvaluationDescriptionActivity", RouteMeta.build(RouteType.ACTIVITY, GradeEvaluationDescriptionActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/HealthDataDetailActivity", RouteMeta.build(RouteType.ACTIVITY, HealthDataDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/HealthDataHistoryActivity", RouteMeta.build(RouteType.ACTIVITY, HealthDataHistoryActivity.class, -1, 16777216, null));
        map.put("/Main/HealthDatasActivity", RouteMeta.build(RouteType.ACTIVITY, HealthDatasActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/HealthKitThirdPartyAccountAuthActivity", RouteMeta.build(RouteType.ACTIVITY, HealthKitThirdPartyAccountAuthActivity.class, -1, 16777216, null));
        map.put("/Main/InputBloodPressureActivity", RouteMeta.build(RouteType.ACTIVITY, InputBloodPressureActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/InputWeightActivity", RouteMeta.build(RouteType.ACTIVITY, InputWeightActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/InvoiceApplicationActivity", RouteMeta.build(RouteType.ACTIVITY, InvoiceApplicationActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/KnitActiveHoursActivity", RouteMeta.build(RouteType.ACTIVITY, KnitActiveHoursActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/KnitActiveRecordActivity", RouteMeta.build(RouteType.ACTIVITY, KnitActiveRecordActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/KnitBloodPressureActivity", RouteMeta.build(RouteType.ACTIVITY, KnitBloodPressureActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/KnitPressureActivity", RouteMeta.build(RouteType.ACTIVITY, KnitPressureActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/KnitRelaxActivity", RouteMeta.build(RouteType.ACTIVITY, KnitRelaxActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/KnitSleepDetailActivity", RouteMeta.build(RouteType.ACTIVITY, KnitSleepDetailActivity.class, -1, 16777216, null));
        map.put("/Main/KnitSleepTightActivity", RouteMeta.build(RouteType.ACTIVITY, KnitSleepTightActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/LightFastingStatusActivity", RouteMeta.build(RouteType.ACTIVITY, LightFastingStatusActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/MyRouteDetailActivity", RouteMeta.build(RouteType.ACTIVITY, MyRouteDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/PressureCalibrateActivity", RouteMeta.build(RouteType.ACTIVITY, PressureCalibrateActivity.class, -1, 16777216, null));
        map.put("/Main/PressureMeasureActivity", RouteMeta.build(RouteType.ACTIVITY, PressureMeasureActivity.class, -1, 16777216, null));
        map.put("/Main/PrivacyCenterActivity", RouteMeta.build(RouteType.ACTIVITY, PrivacyCenterActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/PrivacyDataModelActivity", RouteMeta.build(RouteType.ACTIVITY, PrivacyDataModelActivity.class, -1, 16777216, null));
        map.put("/Main/PrivacyTrainingStatisticsActivity", RouteMeta.build(RouteType.ACTIVITY, PrivacyTrainingStatisticsActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/QuestionMainActivity", RouteMeta.build(RouteType.ACTIVITY, QuestionMainActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/SeriesCourseListActivity", RouteMeta.build(RouteType.ACTIVITY, SeriesCourseListActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/SportHistoryActivity", RouteMeta.build(RouteType.ACTIVITY, SportHistoryActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/ThirdPartySyncActivity", RouteMeta.build(RouteType.ACTIVITY, ThirdPartySyncActivity.class, -1, 16777216, null));
        map.put("/Main/ThreeCirclePretreatment", RouteMeta.build(RouteType.HANDLER, ThreeCirclePretreatment.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/WeightAiBodyDataActivity", RouteMeta.build(RouteType.ACTIVITY, WeightAiBodyDataActivity.class, -1, 16777216, null));
        map.put("/Main/WeightBodyDataActivity", RouteMeta.build(RouteType.ACTIVITY, WeightBodyDataActivity.class, -1, 16777216, null));
        map.put("/Main/WeightDetailActivity", RouteMeta.build(RouteType.ACTIVITY, WeightDetailActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/WeightEditShareActivity", RouteMeta.build(RouteType.ACTIVITY, WeightEditShareActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/WeightGoalActivity", RouteMeta.build(RouteType.ACTIVITY, WeightGoalActivity.class, -1, 16777216, null));
        map.put("/Main/WeightGoalPreviewActivity", RouteMeta.build(RouteType.ACTIVITY, WeightGoalPreviewActivity.class, -1, 16777216, null));
        map.put("/Main/WeightUnitSettingActivity", RouteMeta.build(RouteType.ACTIVITY, WeightUnitSettingActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/WeightUserManagerActivity", RouteMeta.build(RouteType.ACTIVITY, WeightUserManagerActivity.class, -1, Integer.MIN_VALUE, null));
        map.put("/Main/WifiDevicePressureCalibrateGuideActivity", RouteMeta.build(RouteType.ACTIVITY, WifiDevicePressureCalibrateGuideActivity.class, -1, 16777216, null));
        map.put("/Main/service/pretreatment", RouteMeta.build(RouteType.HANDLER, SleepServiceImpl.class, -1, Integer.MIN_VALUE, null));
    }
}
